// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PurpleSkyTTRPG.DataAccess.Postgres;

#nullable disable

namespace PurpleSkyTTRPG.DataAccess.Postgres.Migrations
{
    [DbContext(typeof(TTRPGDbContext))]
    [Migration("20260321142417_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.CharacterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CharData")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("System")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyCharacterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("LobbyId");

                    b.ToTable("LobbyCharacters");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyCharacterNoteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LobbyCharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("NoteVisibility")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LobbyCharacterId");

                    b.ToTable("LobbyCharacterNotes");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GmId")
                        .HasColumnType("uuid");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("System")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GmId");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyInventoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContributorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LobbyEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ProfileEntityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ContributorId");

                    b.HasIndex("LobbyEntityId");

                    b.HasIndex("LobbyId");

                    b.HasIndex("ProfileEntityId");

                    b.ToTable("LobbyInventories");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.HasIndex("ProfileId");

                    b.ToTable("LobbyProfiles");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.NoteVisibilityEntity", b =>
                {
                    b.Property<Guid>("LobbyCharacterNoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LobbyProfileEntityId")
                        .HasColumnType("uuid");

                    b.HasKey("LobbyCharacterNoteId", "ProfileId");

                    b.HasIndex("LobbyProfileEntityId");

                    b.HasIndex("ProfileId");

                    b.ToTable("NoteVisibilities");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.ProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.SystemItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemTag")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int>("System")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("System");

                    b.ToTable("SystemItems");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.SystemSkillEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("System")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("System");

                    b.ToTable("SystemSkills");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.SystemSpellEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("System")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("System");

                    b.ToTable("SystemSpells");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyCharacterEntity", b =>
                {
                    b.HasOne("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.CharacterEntity", "Character")
                        .WithMany("LobbyCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyEntity", "Lobby")
                        .WithMany("LobbyCharacters")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Lobby");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyCharacterNoteEntity", b =>
                {
                    b.HasOne("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyCharacterEntity", "LobbyCharacter")
                        .WithMany("LobbyCharacterNotes")
                        .HasForeignKey("LobbyCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LobbyCharacter");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyEntity", b =>
                {
                    b.HasOne("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.ProfileEntity", "Profile")
                        .WithMany("Lobbies")
                        .HasForeignKey("GmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyInventoryEntity", b =>
                {
                    b.HasOne("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.ProfileEntity", "Profile")
                        .WithMany()
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyEntity", null)
                        .WithMany("LobbyInventories")
                        .HasForeignKey("LobbyEntityId");

                    b.HasOne("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyEntity", "Lobby")
                        .WithMany()
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.ProfileEntity", null)
                        .WithMany("LobbyInventories")
                        .HasForeignKey("ProfileEntityId");

                    b.Navigation("Lobby");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyProfileEntity", b =>
                {
                    b.HasOne("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyEntity", "Lobby")
                        .WithMany("LobbyProfiles")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.ProfileEntity", "Profile")
                        .WithMany("LobbyProfiles")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.NoteVisibilityEntity", b =>
                {
                    b.HasOne("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyCharacterNoteEntity", "LobbyCharacterNote")
                        .WithMany("NoteVisibilities")
                        .HasForeignKey("LobbyCharacterNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyProfileEntity", null)
                        .WithMany("NoteVisibilities")
                        .HasForeignKey("LobbyProfileEntityId");

                    b.HasOne("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.ProfileEntity", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LobbyCharacterNote");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.CharacterEntity", b =>
                {
                    b.Navigation("LobbyCharacters");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyCharacterEntity", b =>
                {
                    b.Navigation("LobbyCharacterNotes");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyCharacterNoteEntity", b =>
                {
                    b.Navigation("NoteVisibilities");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyEntity", b =>
                {
                    b.Navigation("LobbyCharacters");

                    b.Navigation("LobbyInventories");

                    b.Navigation("LobbyProfiles");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.LobbyProfileEntity", b =>
                {
                    b.Navigation("NoteVisibilities");
                });

            modelBuilder.Entity("PurpleSkyTTRPG.DataAccess.Postgres.Persistence.ProfileEntity", b =>
                {
                    b.Navigation("Lobbies");

                    b.Navigation("LobbyInventories");

                    b.Navigation("LobbyProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
